DELETE FROM foreign_universities;
DELETE FROM visa_guides;
DELETE FROM consultants;

-- Foreign Universities (30)
INSERT INTO foreign_universities (university_name, university_slug, country, qs_rank, acceptance_rate, tuition_usd_annual, living_cost_usd_monthly, intake_months, official_url, min_ielts, min_toefl, min_gre, scholarship_available, description, city, institution_type, application_fee_usd, min_pte, min_gpa, degrees_offered) VALUES
('Massachusetts Institute of Technology','mit-cambridge','USA',1,3.9,57986,2500,'["September","February"]','https://www.mit.edu',7.0,100,325,1,'MIT is a world-renowned research university known for science, engineering, and technology.','Cambridge','Private',75,70,3.9,'["Bachelors","Masters","PhD"]'),
('Stanford University','stanford-california','USA',2,3.6,56169,2800,'["September"]','https://www.stanford.edu',7.0,100,320,1,'Stanford is a leading research university in Silicon Valley known for entrepreneurship.','Palo Alto','Private',90,70,3.9,'["Bachelors","Masters","PhD"]'),
('Harvard University','harvard-cambridge','USA',4,3.2,54768,2600,'["September"]','https://www.harvard.edu',7.0,100,325,1,'Harvard is the oldest and most prestigious university in the world.','Cambridge','Private',75,70,3.9,'["Bachelors","Masters","PhD"]'),
('California Institute of Technology','caltech-pasadena','USA',6,2.7,58680,2400,'["September"]','https://www.caltech.edu',7.0,100,330,1,'Caltech is a world-renowned science and engineering research institute.','Pasadena','Private',85,70,3.9,'["Bachelors","Masters","PhD"]'),
('University of Chicago','uchicago-chicago','USA',11,5.3,60963,2200,'["September","January"]','https://www.uchicago.edu',7.0,104,325,1,'Leading research university known for rigorous academics and economics.','Chicago','Private',75,70,3.9,'["Bachelors","Masters","PhD"]'),
('University of Pennsylvania','upenn-philadelphia','USA',13,5.7,58620,2100,'["August"]','https://www.upenn.edu',7.0,100,320,1,'Ivy League university known for Wharton business school.','Philadelphia','Private',75,70,3.8,'["Bachelors","Masters","PhD"]'),
('UC Berkeley','ucb-berkeley','USA',15,11.6,44008,2300,'["August","January"]','https://www.berkeley.edu',7.0,100,310,1,'Top public university known for research and innovation.','Berkeley','Public',80,64,3.7,'["Bachelors","Masters","PhD"]'),
('UCLA','ucla-losangeles','USA',29,8.7,43022,2200,'["September"]','https://www.ucla.edu',7.0,100,300,1,'Leading public research university in Los Angeles.','Los Angeles','Public',80,64,3.7,'["Bachelors","Masters","PhD"]'),
('Columbia University','columbia-newyork','USA',19,3.7,63530,2800,'["September","January"]','https://www.columbia.edu',7.0,101,320,1,'Ivy League university in New York City.','New York','Private',85,69,3.7,'["Bachelors","Masters","PhD"]'),
('Yale University','yale-newhaven','USA',16,4.4,59950,2200,'["December"]','https://www.yale.edu',7.0,100,325,1,'Known for outstanding arts, humanities, and law programs.','New Haven','Private',80,70,3.9,'["Bachelors","Masters","PhD"]'),
('University of Oxford','oxford-oxford','UK',2,14.5,42083,1800,'["September","January"]','https://www.ox.ox.ac.uk',7.5,110,310,1,'Oldest university in the English-speaking world.','Oxford','Public',75,67,3.7,'["Bachelors","Masters","PhD"]'),
('University of Cambridge','cambridge-cambridge','UK',3,18.6,37023,1700,'["September"]','https://www.cam.ac.uk',7.5,110,310,1,'World-leading university with centuries of academic excellence.','Cambridge','Public',75,70,3.8,'["Bachelors","Masters","PhD"]'),
('Imperial College London','imperial-london','UK',6,11.0,40240,1900,'["September","January"]','https://www.imperial.ac.uk',7.0,100,310,1,'Science-focused university for engineering, medicine, and business.','London','Public',75,70,3.7,'["Bachelors","Masters","PhD"]'),
('UCL London','ucl-london','UK',9,11.8,35480,1800,'["September"]','https://www.ucl.ac.uk',7.0,100,300,1,'Multidisciplinary university in central London.','London','Public',80,67,3.5,'["Bachelors","Masters","PhD"]'),
('University of Edinburgh','edinburgh-edinburgh','UK',15,11.4,30540,1500,'["September"]','https://www.ed.ac.uk',7.0,100,300,1,'World-leading university known for AI research and humanities.','Edinburgh','Public',75,67,3.5,'["Bachelors","Masters","PhD"]'),
('University of Toronto','uoft-toronto','Canada',21,42.5,57020,1500,'["September","January"]','https://www.utoronto.ca',6.5,100,310,1,'Canadas top university with global research reputation.','Toronto','Public',90,60,3.7,'["Bachelors","Masters","PhD"]'),
('University of British Columbia','ubc-vancouver','Canada',34,46.0,42981,1400,'["September","January"]','https://www.ubc.ca',6.5,90,300,1,'Leading global university known for sustainability.','Vancouver','Public',80,60,3.4,'["Bachelors","Masters","PhD"]'),
('McGill University','mcgill-montreal','Canada',30,41.0,25274,1300,'["September","January"]','https://www.mcgill.ca',6.5,90,300,1,'One of Canadas most prestigious universities.','Montreal','Public',75,60,3.5,'["Bachelors","Masters","PhD"]'),
('University of Waterloo','waterloo-waterloo','Canada',112,53.0,53397,1200,'["September"]','https://uwaterloo.ca',6.5,90,300,0,'Known for co-op programs and engineering excellence.','Waterloo','Public',80,60,3.5,'["Bachelors","Masters","PhD"]'),
('University of Alberta','ualberta-edmonton','Canada',110,48.0,29580,1100,'["September","January"]','https://www.ualberta.ca',6.5,86,300,1,'Top research university in Western Canada.','Edmonton','Public',75,60,3.3,'["Bachelors","Masters","PhD"]'),
('University of Melbourne','unimelb-melbourne','Australia',13,69.0,47280,1500,'["February","July"]','https://www.unimelb.edu.au',6.5,79,300,1,'Australias top-ranked university for research.','Melbourne','Public',100,58,3.5,'["Bachelors","Masters","PhD"]'),
('University of Sydney','usyd-sydney','Australia',18,55.5,46000,1600,'["February","July"]','https://www.sydney.edu.au',6.5,85,300,1,'Leading research university with strong industry connections.','Sydney','Public',100,58,3.5,'["Bachelors","Masters","PhD"]'),
('Australian National University','anu-canberra','Australia',30,35.0,44420,1400,'["February","July"]','https://www.anu.edu.au',6.5,80,300,1,'Leading research university in public policy and sciences.','Canberra','Public',100,58,3.5,'["Bachelors","Masters","PhD"]'),
('UNSW Sydney','unsw-sydney','Australia',19,61.0,47760,1500,'["February","September"]','https://www.unsw.edu.au',6.5,85,300,1,'Known for engineering, business, and law programs.','Sydney','Public',100,58,3.5,'["Bachelors","Masters","PhD"]'),
('TU Munich','tum-munich','Germany',37,8.0,163,1100,'["October","April"]','https://www.tum.de',6.5,88,310,1,'Germanys top technical university with tuition-free education.','Munich','Public',0,58,3.0,'["Bachelors","Masters","PhD"]'),
('LMU Munich','lmu-munich','Germany',63,20.0,163,1100,'["October"]','https://www.lmu.de',6.5,80,300,1,'Leading university in humanities and sciences.','Munich','Public',0,58,3.0,'["Bachelors","Masters","PhD"]'),
('Heidelberg University','heidelberg-heidelberg','Germany',65,18.0,163,1000,'["October"]','https://www.uni-heidelberg.de',6.5,80,300,1,'Germanys oldest university known for medicine and sciences.','Heidelberg','Public',0,58,3.0,'["Bachelors","Masters","PhD"]'),
('National University of Singapore','nus-singapore','Singapore',8,5.0,38200,1500,'["August","January"]','https://www.nus.edu.sg',6.5,92,320,1,'Asias top university for global research and innovation.','Singapore','Public',20,62,3.7,'["Bachelors","Masters","PhD"]'),
('Nanyang Technological University','ntu-singapore','Singapore',15,12.0,34800,1400,'["August","January"]','https://www.ntu.edu.sg',6.5,90,300,1,'Known for engineering and technology research.','Singapore','Public',20,62,3.5,'["Bachelors","Masters","PhD"]'),
('University of Hong Kong','hku-hongkong','Hong Kong',26,15.0,43200,1400,'["September","January"]','https://www.hku.hk',6.5,80,300,1,'Oldest university in Hong Kong with strong global ties.','Hong Kong','Public',50,62,3.5,'["Bachelors","Masters","PhD"]');

-- Visa Guides (8 countries)
INSERT INTO visa_guides (country, visa_type, processing_time_days, visa_fee_usd, documents_required, success_tips, pswv_duration_months, proof_of_funds_usd, interview_required, part_time_work_hours) VALUES
('USA','F-1 Student Visa',60,185,'["Passport","I-20","DS-160","SEVIS fee","Financial proof","Academic transcripts","English proficiency test"]','Apply early, prepare for visa interview, show strong ties to home country.',12,25000,1,20),
('UK','Student Visa (Tier 4)',15,490,'["CAS letter","Passport","TB test","Financial proof","ATAS certificate","English proficiency"]','Apply as soon as CAS is received, ensure financial requirements are met.',6,13347,0,20),
('Canada','Study Permit',45,150,'["LOA from DLI","Passport","Financial proof","Medical exam","Police clearance","Digital photograph"]','Apply online, provide strong financial evidence, write a convincing SOP.',6,20635,0,20),
('Australia','Student Visa (Subclass 500)',42,710,'["CoE","OSHC","Passport","GTE statement","Financial proof","English proficiency","Health exam"]','Demonstrate GTE requirement, show sufficient funds, maintain health insurance.',6,24505,0,48),
('Germany','Student Visa',25,75,'["University admission","Blocked account","Passport","Health insurance","APS certificate"]','Open blocked account early, get APS certificate if from India.',18,11208,0,20),
('Singapore','Student Pass',15,30,'["IPA letter","Passport","Financial proof","Medical examination","Academic transcripts"]','Apply online through SOLAR, ensure university submits application on time.',0,0,0,16),
('Ireland','Student Visa (Stamp 2)',40,80,'["Letter of acceptance","Financial proof","Medical insurance","English proficiency","Passport"]','Show 7000 EUR plus 10000 EUR per year of study.',6,11500,0,20),
('New Zealand','Student Visa',30,330,'["Offer of Place","Passport","Financial proof","Medical certificate","Police clearance"]','Show NZD 20000 per year for living costs.',12,15000,0,20);

-- Consultants (10)
INSERT INTO consultants (consultant_name, slug, consultant_rating, verified_consultant, specialization_countries, fee_range, contact_email, contact_phone, city, experience_years, specializations, consultation_mode, success_rate_percent, office_location, languages_spoken, website_url, bio) VALUES
('IDP Education','idp-education',4.6,1,'["Australia","Canada","UK","USA","New Zealand"]','INR 5000 - 15000','info@idp.com','+91-124-4514514','New Delhi',30,'Study Abroad, Visa Assistance, University Selection','Both',95,'Nehru Place, New Delhi','English, Hindi','https://www.idp.com','IDP Education is a global leader in international student placement with offices in 50+ countries.'),
('British Council','british-council',4.7,1,'["UK"]','Free',' enquiries@britishcouncil.org','+91-124-4518100','New Delhi',85,'Study in UK, IELTS, Scholarships','Both',92,'Barakhamba Road, New Delhi','English, Hindi','https://www.britishcouncil.in','The UKs international cultural relations organization helping students study in the UK.'),
('Shiksha Study Abroad','shiksha-abroad',4.4,1,'["USA","UK","Canada","Australia","Germany","Singapore"]','INR 0 (Free Counseling)','counsel@shiksha.com','+91-9876543210','Gurgaon',15,'University Selection, Application, SOP Review, Visa','Online',88,'Cyber City, Gurgaon','English, Hindi','https://www.shiksha.com/abroad','Shiksha is Indias largest education marketplace with free counseling services.'),
('Study Abroad Counselling Service','sacs-mumbai',4.3,1,'["USA","UK","Canada","Australia"]','INR 8000 - 20000','info@sacs.com','+91-22-45678900','Mumbai',12,'MBA Abroad, MS Abroad, PhD Abroad','Both',85,'Andheri West, Mumbai','English, Hindi, Marathi','https://www.sacs.in','Specialized counseling for graduate admissions to top universities worldwide.'),
('Educomp Study Abroad','educomp-abroad',4.2,0,'["USA","Canada","Australia"]','INR 10000 - 25000','abroad@educomp.com','+91-11-45678901','New Delhi',18,'Undergraduate, Graduate, Test Prep (SAT, GRE, GMAT)','Both',82,'Noida, UP','English, Hindi','https://www.educomp.com','Educomp provides end-to-end solutions for students planning to study abroad.'),
('Global Study Partners','gsp-hyderabad',4.5,1,'["USA","UK","Canada","Germany"]','INR 5000 - 12000','info@gsp.in','+91-40-45678902','Hyderabad',10,'Engineering, Computer Science, Business Schools','Online',90,'Banjara Hills, Hyderabad','English, Hindi, Telugu','https://www.gsp.in','GSP connects Indian students with partner universities for direct admissions.'),
('Meridian Global Studies','meridian-pune',4.1,0,'["UK","Australia","New Zealand","Ireland"]','INR 7000 - 18000','contact@meridian.com','+91-20-45678903','Pune',8,'Foundation Programs, Pathway Programs, Undergraduate','Both',80,'Kothrud, Pune','English, Hindi, Marathi','https://www.meridian-studies.com','Meridian specializes in pathway and foundation programs for international students.'),
('Canam Consultants','canam',4.0,1,'["Canada","USA","UK","Australia","Singapore"]','INR 3000 - 10000','info@canam.com','+91-172-45678904','Chandigarh',28,'Student Visa, Immigration, Study Permits','Both',87,'Sector 17, Chandigarh','English, Hindi, Punjabi','https://www.canamgroup.com','Canam is one of Indias largest overseas education and immigration consultancies.'),
('The Chopras','the-chopras',4.3,1,'["USA","UK","Canada","Germany","Singapore"]','Free Counseling','query@thechopras.com','+91-11-45678905','New Delhi',35,'End-to-End Admission, Scholarships, Test Prep','Both',91,'South Delhi','English, Hindi','https://www.thechopras.com','The Chopras have been guiding students to global universities since 1995.'),
('Manya Education','manya-education',4.2,0,'["USA","UK","Canada","Australia"]','INR 5000 - 15000','info@manyagroup.com','+91-11-45678906','New Delhi',20,'GRE, GMAT, SAT, TOEFL, IELTS, Study Abroad','Both',84,'CP, New Delhi','English, Hindi','https://www.manyagroup.com','Manya Education is a leading test prep and study abroad counseling organization.');
