-- 1. Predictor Configuration Table
-- Stores the algorithm weights, offsets, and rules for predicting colleges per exam per year
CREATE TABLE predictor_config (
    id VARCHAR(36) PRIMARY KEY, -- Use UUID()
    exam_id VARCHAR(36) NOT NULL, -- FK to exams table
    
    model_weights JSON NOT NULL, -- e.g. {"rank":0.5, "category":0.3, "state":0.2}
    data_year YEAR NOT NULL,
    prediction_accuracy FLOAT DEFAULT NULL, -- Last backtested accuracy
    
    min_score INT DEFAULT 0,
    max_score INT NOT NULL,
    
    category_adjustments JSON DEFAULT NULL, -- Rank band offsets by category
    
    state_quota_enabled BOOLEAN DEFAULT FALSE,
    home_state_quota_pct FLOAT DEFAULT 0.0,
    counselling_round_model TINYINT DEFAULT 1, -- Rounds to simulate
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
    UNIQUE(exam_id, data_year) -- Only one active config per exam per year
);

-- 2. Predictor Submissions & Results
-- Stores the data entered by students and the results generated by the algorithm
CREATE TABLE predictor_submissions (
    id VARCHAR(36) PRIMARY KEY, -- Use UUID()
    user_id VARCHAR(36) DEFAULT NULL, -- Null if anonymous/guest
    exam_id VARCHAR(36) NOT NULL, -- FK to exams table
    
    score INT DEFAULT NULL,
    rank INT DEFAULT NULL,
    percentile FLOAT DEFAULT NULL,
    
    category ENUM('General', 'OBC', 'SC', 'ST', 'EWS', 'PwD') DEFAULT 'General',
    preferred_state VARCHAR(100) DEFAULT NULL,
    preferred_course_id VARCHAR(36) DEFAULT NULL, -- FK to courses table
    
    results JSON DEFAULT NULL, -- Array of objects: [{college_id, probability, tier, match_factors}]
    share_token VARCHAR(255) UNIQUE NOT NULL, -- For public sharing links
    
    lead_captured BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Assuming users, exams, and courses tables exist with VARCHAR(36) UUIDs
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
    FOREIGN KEY (preferred_course_id) REFERENCES courses(id) ON DELETE SET NULL
);
