CREATE TABLE IF NOT EXISTS `scholarships` (
    `id` CHAR(36) PRIMARY KEY,
    `scholarship_name` VARCHAR(255) NOT NULL,
    `scholarship_slug` VARCHAR(255) UNIQUE NOT NULL,
    `provider_name` VARCHAR(255) NULL,
    `provider_logo` VARCHAR(255) NULL,
    `scholarship_type` ENUM('government','private','college','abroad','sports','minority') NULL,
    `amount` DECIMAL(10,2) NULL,
    `amount_type` ENUM('fixed','percentage','full_tuition','stipend') NULL,
    `eligibility_criteria` TEXT NULL,
    `min_percentage` FLOAT NULL,
    `income_limit` DECIMAL(12,2) NULL,
    `gender` ENUM('all','male','female','transgender') DEFAULT 'all',
    `category` ENUM('all','sc','st','obc','ews','minority','pwd') DEFAULT 'all',
    `state_specific` VARCHAR(255) NULL,
    `course_levels` JSON NULL COMMENT 'JSON array of course levels',
    `apply_start` DATE NULL,
    `apply_end` DATE NULL,
    `official_link` VARCHAR(255) NULL,
    `renewable` BOOLEAN DEFAULT FALSE,
    `renewable_conditions` TEXT NULL,
    `status` ENUM('active','expired','upcoming') DEFAULT 'upcoming',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
